### PR TITLE
Add support for Rails 7.2

### LINKED ISSUE #82: Rails 7.2 support
Hey there, thanks for creating and maintaining this gem!

I was wondering what we need in order to also support the [recently released Rails 7.2 version](https://rubyonrails.org/2024/8/10/Rails-7-2-0-has-been-released). From what I can tell, it's been running fine on `7.2.0.beta3` but is now being held back by the ActiveRecord `< 7.2` requirement in the gemspec.

Is there anything we need to update or something I can help with to make `pg_party` work with Rails 7.2+?

Thank you!

### PR DESCRIPTION
**Pull request by marcoroth**
This pull request attempts to add support for Rails 7.2.  

Resolves #82

### CODE REVIEW

**Comment by marcoroth** [comment]
I noticed that there are quite a number of failing tests which look something like:

```ruby
NoMethodError:
  undefined method `hash' for an instance of BasicObject

NoMethodError:
  undefined method `is_a?' for an instance of BasicObject
```

I was able to trace it down to any call on a model that uses any of the `pg_party` methods:

```ruby
described_class.create(...)
```

With a little more tracing I noticed that it's any ActiveRecord-adjecent call, so I was able to reproduce it by calling `#primary_key` on the model. 

```ruby
❯ bin/console
[1] pry(main)> BigintBooleanList.primary_key
=> #<BasicObject:0x1b44>
[2] pry(main)>
```

For reference, on Rails 7.1 this returns `"id"`:

```ruby
❯ bin/console
[1] pry(main)> Rails::VERSION::STRING
=> "7.1.3.4"
[2] pry(main)> BigintBooleanList.primary_key
=> "id"
```

I'm not quite sure what's causing this, but it seems that this refactor might be related: https://github.com/rails/rails/pull/49808

**Comment by marcoroth** [comment]
Okay interesting, when I revert the `primary_key` implementation back to the [Rails 7.1 version](https://github.com/rails/rails/blob/cfa059b3538179602763f96d5a22e4ea42c26b4e/activerecord/lib/active_record/attribute_methods/primary_key.rb#L111C2-L116C14) all tests pass:

```ruby
def primary_key
  if PRIMARY_KEY_NOT_SET.equal?(@primary_key)
    @primary_key = reset_primary_key
  end
  @primary_key
end
```

The main difference between the two versions is that the 7.1 version assigns the return value of `reset_primary_key` to `@primary_key`, which the 7.2 version doesn't. I'm wondering if this was on purpose, since the 7.2 version also calls `reset_primary_key` but doesn't assign the return value

**Comment by marcoroth** [comment]
I monkey patched `ActiveRecord::AttributeMethods::PrimaryKey::primary_key` for now so my CI can pass, but we obviously need to remove that patch later.

**Comment by marcoroth** [comment]
Looks like this is ready for review, let me know if there's something else that needs to be addressed! 🙌🏼

**Comment by igor-alexandrov** [comment]
Great work @marcoroth.

**Review by igor-alexandrov — APPROVED** [review]

**Comment by igor-alexandrov** [comment]
@rkrage did you have a time to look at this?

**Comment by rkrage** [comment]
Sorry for the delay. Thanks for tracking this down!

I'll merge this and will try to cut a new release at some point today

**Comment by marcoroth** [comment]
Awesome, thank you @rkrage! 🙌🏼 

Let me know if I need to tweak something

**Comment by igor-alexandrov** [comment]
Thank you @rkrage!
